---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.6

suites:
  - name: default
    run_list:
      - recipe[jemalloc::default]
      - recipe[openresty::default]
      - recipe[openresty::luarocks]
    attributes:
      openresty:
        default_site_enabled: true
        link_to_jemalloc: true
        luarocks:
          default_rocks:
            luaproc: '1.0-3'
